DOC?= book 

FORMATS?= html-split html
MAINTAINER= murat@enderunix.org

INSTALL_COMPRESSED?=gz

SRCS= book.sgml

DOC_PREFIX?= /usr/doc
#DESTDIR= /home/murat/public_html/
DESTDIR= ../users-manual

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
